server:
  port: ${API_PORT}

spring:
  application:
    name: knutice-api

  # Mongo 자동구성 비활성화
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

  data:
    mongodb:
      primary:
        uri: ${MONGO_PRIMARY_URI}
        database: ${MONGO_DATABASE}
      secondary:
        uri: ${MONGO_SECONDARY_URI}
        database: ${MONGO_DATABASE}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  access-token:
    plus-hour: ${JWT_ACCESS_PLUS_HOUR}
  refresh-token:
    plus-hour: ${JWT_REFRESH_PLUS_HOUR}

file:
  upload-dir: ${FILE_UPLOAD_DIR}
  context-path: ${FILE_CONTEXT_PATH}

url:
  scheme: ${URL_SCHEME}
  host: ${URL_HOST}

webhook:
  slack:
    url: ${WEBHOOK_SLACK_URL}

logging:
  level:
    org:
      springframework.web: DEBUG
      hibernate: INFO

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  metrics:
    tags:
      application: ${spring.application.name}

crawler:
  server:
    address: ${CRAWLER_SERVER_ADDRESS}
