name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Test Gradle
    runs-on: ubuntu-latest
    environment: PRD
    env:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_PRD }}
    steps:
      - uses: ./.github/actions/common

      - name: Run Tests
        run: doppler run -- ./gradlew test

  docker:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: build
    environment: PRD
    env:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_PRD }}
    steps:
      - uses: ./.github/actions/common

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create firebase_service_key.json
        run: |
          mkdir -p crawler/src/main/resources/firebase
          echo "${{ secrets.FIREBASE_SERVICE_KEY }}" > crawler/src/main/resources/firebase/firebase_service_key.json

      - name: Build JARs
        run: doppler run -- ./gradlew clean :api:bootJar :crawler:bootJar

      - name: Build & Push Docker Images
        run: |
          doppler run -- docker compose build
          doppler run -- docker compose push

  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    needs: docker
    environment: PRD
    env:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_PRD }}
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PEM_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /home/ubuntu
            
            export DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN_PRD }}
            
            if [ -d KNUTICE-SERVER-V2 ]; then rm -rf KNUTICE-SERVER-V2; fi
            git clone https://github.com/KNUTICE/KNUTICE-SERVER-V2.git
            
            cd KNUTICE-SERVER-V2
            doppler run -- docker compose pull
            doppler run -- docker compose up -d
            docker image prune -f
            
            cd ..
            rm -rf KNUTICE-SERVER-V2