name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    environment: PRD
    env:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_PRD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create firebase_service_key.json
        run: |
          mkdir -p crawler/src/main/resources/firebase
          echo "${{ secrets.FIREBASE_SERVICE_KEY }}" > crawler/src/main/resources/firebase/firebase_service_key.json

      - name: Build & Push Docker Images
        run: |
          doppler run -- docker compose build
          doppler run -- docker compose push

      - name: Deploy on Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PEM_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /home/ubuntu
            
            export DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN_PRD }}            
            
            if [ -d KNUTICE-SERVER-V2 ]; then rm -rf KNUTICE-SERVER-V2; fi
            git clone https://github.com/KNUTICE/KNUTICE-SERVER-V2.git
           
            cd KNUTICE-SERVER-V2
            doppler run -- docker compose pull
            doppler run -- docker compose up -d
            docker image prune -f
           
            cd ..
            rm -rf KNUTICE-SERVER-V2